safe: false
permalink: pretty

gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll_version_plugin
  - bootstrap-sass
  - font-awesome-sass
  - mini_magick

assets:
  - "*.svg"

assets:
    js_compressor: yui

sources:
  - _assets/images/icons

exclude: [.gitignore, Gemfile, Gemfile.lock, README.md, Rakefile, build, deploy.sh]
